server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/windsorfood?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
  rabbitmq:
      host: 192.168.2.155
      username: maple
      password: maple
      virtual-host: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.sengou.user.pojo