server:
  port: 10010
spring:
  application:
    name: sengou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/**  # 商品微服务的映射路径
    search-service: /search/** #搜索微服务的映射路径
    user-service: /user/** #用户微服务
    auth-service: /auth/** # 授权中心微服务
    cart-service: /cart/** # 购物车微服务
    goods-web: /goodsweb/**
  add-host-header: true # 携带请求本身的Header信息
  ignored-patterns: /upload/**
  ignored-services:   # 忽略upload-service服务
            - upload-service
  sensitive-headers:  # 配置禁止使用的header信息，设置这里为null，否则，set-cookie无效

