server:
  port: 9000
spring:
  application:
    name: item-service
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/windsorfood?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 10 # 10秒即过期
    lease-renewal-interval-in-seconds: 5 # 5秒一次心跳
mybatis:
  type-aliases-package: com.sengou.item.com.sengou.item.pojo

