server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.2.155
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10 #间隔多久去拉去服务注册信息
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒心跳
    lease-expiration-duration-in-seconds: 15 #15秒即过期
sengou:
  jwt:
    pubKeyPath: D:\gitWarehouse\sengouproject\rsa\\rsa.pub # 公钥地址
    cookieName: SG_TOKEN # cookie的名称